# This pipeline is used to train a model on the F3 dataset using the UNet architecture.
# The model is defined in Framework-SSL/configs/models/single_channel_unet.yaml.
# The data module is defined in Framework-SSL/configs/data/f3_reconstruct_data.yaml.
# The trainer is defined in Framework-SSL/configs/trainer/default.yaml.

# --------------------- INIT ARGS ---------------------
# Model configuration file
model: "/workspaces/seismic/Framework-SSL/configs/models/single_channel_unet.yaml"
# Trainer configuration file
trainer: "/workspaces/seismic/Framework-SSL/configs/trainer/default.yaml"
log_dir: null
# --------------------- RUN ARGS (Pipeline's entry-point) ---------------------
run:
  # Set the task to train
  task: fit
  # Data configuration file
  data: "/workspaces/seismic/Framework-SSL/configs/data/f3_reconstruct_data.yaml"