# Evalute a trained model on random reconstruction data
# The model is defined in Framework-SSL/configs/models/single_channel_unet.yaml.
# The trainer is defined in Framework-SSL/configs/trainer/default.yaml.
# The data module is defined in Framework-SSL/configs/data/random_reconstruction_data.yaml.
# The model is evaluated using the last checkpoint from the training process.
# The mse and mae metrics are used to evaluate the model.

# --------------------- INIT ARGS ---------------------
# Model configuration file
model: "/workspaces/seismic/Framework-SSL/configs/models/single_channel_unet.yaml"
# Trainer configuration file
trainer: "/workspaces/seismic/Framework-SSL/configs/trainer/default.yaml"
# Regression metrics to evaluate the model
regression_metrics: 
  mse:
    class_path: torchmetrics.regression.MeanSquaredError
    init_args: {}
  mae:
    class_path: torchmetrics.regression.MeanAbsoluteError
    init_args: {}
log_dir: null
# --------------------- RUN ARGS (Pipeline's entry-point) ---------------------
run:
  data: "/workspaces/seismic/Framework-SSL/configs/data/random_reconstruction_data.yaml"
  task: evaluate
  